URL_SERVICE ="https://cnt-bfaabb8d-d8ac-4fd7-8c4d-fa231f60d2f0.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
KITS_TABLE_PATH = "/api/db/resources/kit_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
KITS_PATH = "/api/v1/kits"