URL_SERVICE ="https://cnt-df94b69a-24fa-4e79-9ac8-cb71e1443e7a.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
KITS_TABLE_PATH = "/api/db/resources/kit_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
KITS_PATH = "/api/v1/kits"